// Generated by https://quicktype.io

export interface AuthResponse {
  code:        string;
  description: string;
  datetime:    string;
  data:        Auth[];
}

export interface Auth {
  updatedAt:          string;
  username:           string;
  accessToken:        string;
  email:              string;
  idUser:             string;
  tokenSecExpiration: number;
  apiCounter:         APICounter;
  nameApp:            string;
}

export interface APICounter {
  current:    number;
  dailyUse:   number;
  owner:      number;
  licenceUse: string;
  aboutUses:  string;
}
